name: "Deployment(DEV) to Firebase."

on:
  push:
    branches:
      - development

jobs:
  deploy_job:
    name: Deploy development version to Firebase
    env:
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - name: Move into 'development' branch
        uses: actions/checkout@v2

      - name: Setup latest v8.* of node and install dependencies.
        uses: actions/setup-node@v2-beta
        with:
          node-version: "10"
      - run: npm i -g firebase-tools
      - run: cd ./functions && npm install
      - run: firebase deploy --token $FIREBASE_TOKEN -P development
